/**
 * Empty default export functions.
 */

module.exports = {
  uniqueId: () => Promise.resolve(''),
  instanceId: () => Promise.resolve(''),
  serialNumber: () => Promise.resolve(''),
  getIpAddress: () => Promise.resolve(''),
  getMacAddress: () => Promise.resolve(''),
  deviceId: () => Promise.resolve(''),
  systemManufacturer: () => Promise.resolve(''),
  model: () => Promise.resolve(''),
  brand: () => Promise.resolve(''),
  systemName: () => Promise.resolve(''),
  systemVersion: () => Promise.resolve(''),
  buildId: () => Promise.resolve(''),
  apiLevel: () => Promise.resolve(0),
  bundleId: () => Promise.resolve(''),
  appName: () => Promise.resolve(''),
  buildNumber: () => Promise.resolve(0),
  appVersion: () => Promise.resolve(0),
  deviceName: () => Promise.resolve(''),
  getUsedMemory: () => Promise.resolve(0),
  userAgent: () => Promise.resolve(''),
  fontScale: () => Promise.resolve(0),
  isEmulator: () => Promise.resolve(false),
  isTablet: () => Promise.resolve(false),
  isPinOrFingerprintSet: () => Promise.resolve(false),
  firstInstallTime: () => Promise.resolve(0),
  installReferrer: () => Promise.resolve(''),
  lastUpdateTime: () => Promise.resolve(0),
  phoneNumber: () => Promise.resolve(''),
  carrier: () => Promise.resolve(''),
  totalMemory: () => Promise.resolve(0),
  maxMemory: () => Promise.resolve(0),
  totalDiskCapacity: () => Promise.resolve(0),
  freeDiskStorage: () => Promise.resolve(0),
  getBatteryLevel: () => Promise.resolve(0),
  isLandscape: () => Promise.resolve(false),
  deviceType: () => Promise.resolve('Unknown'),
  getPowerState: () => Promise.resolve({}),
  hasSystemFeature: () => Promise.resolve(false),
  getSystemAvailableFeatures: () => Promise.resolve([]),
  getCameraPresence: () => Promise.resolve(false),
  isLocationEnabled: () => Promise.resolve(false),
  getAvailableLocationProviders: () => Promise.resolve({}),
};
