require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'example' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'example-app-extension' do
    inherit! :complete
  end

  target 'exampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["CC"] = "clang"
        config.build_settings["LD"] = "clang"
        config.build_settings["CXX"] = "clang++"
        config.build_settings["LDPLUSPLUS"] = "clang++"
      end
    end
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Fix sharedApplication is unavailable: not available on iOS App Extension - Use view controller based solutions where appropriate instead
        # https://stackoverflow.com/questions/52503400/sharedapplication-is-unavailable-not-available-on-ios-app-extension-use-v
        config.build_settings["APPLICATION_EXTENSION_API_ONLY"] = "NO"
      end
    end

    # quiet non-module warnings - only interested in our own warnings
    installer.pods_project.targets.each do |target|
      if !target.name.include? "react-native-device-info"
        target.build_configurations.each do |config|
          config.build_settings["GCC_WARN_INHIBIT_ALL_WARNINGS"] = "YES"
        end
      end
    end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
